// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftwareDesignQueenAnneCuriosityShopProject;

#nullable disable

namespace SoftwareDesignQueenAnneCuriosityShopProject.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251106122323_updatekey")]
    partial class updatekey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Advisory", b =>
                {
                    b.Property<int>("AdvisoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassAdviserID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AdvisoryID");

                    b.HasIndex("ClassAdviserID");

                    b.ToTable("Advisory", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("StudentID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPresent")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttendanceID");

                    b.HasIndex("StudentID");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.ClassAdviser", b =>
                {
                    b.Property<int>("ClassAdviserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50");

                    b.HasKey("ClassAdviserID");

                    b.ToTable("ClassAdviser", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ContactID");

                    b.HasIndex("ParentID");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Delivered", b =>
                {
                    b.Property<int>("DeliveredID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTimeSent")
                        .HasColumnType("datetime");

                    b.Property<int?>("NotificationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeliveredID");

                    b.HasIndex("ContactID");

                    b.HasIndex("NotificationID");

                    b.ToTable("Delivered", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AttendanceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("NotificationID");

                    b.HasIndex("AttendanceID");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Parent", b =>
                {
                    b.Property<int>("ParentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50");

                    b.HasKey("ParentID");

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Relationship", b =>
                {
                    b.Property<int>("RelationshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeOfRelationship")
                        .HasColumnType("varchar(50)");

                    b.HasKey("RelationshipID");

                    b.HasIndex("ParentID");

                    b.HasIndex("StudentID");

                    b.ToTable("Relationship", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdvisoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnrollmentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LRN")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("StudentID");

                    b.HasIndex("AdvisoryID");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("UserID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Advisory", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.ClassAdviser", "ClassAdviserLink")
                        .WithMany("Advisories")
                        .HasForeignKey("ClassAdviserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ClassAdviserLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Attendance", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Student", "StudentLink")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Contact", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Parent", "ParentLink")
                        .WithMany("Contacts")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Delivered", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Contact", "ContactLink")
                        .WithMany("DeliveredMsg")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Notification", "NotificationLink")
                        .WithMany("DeliveredMsg")
                        .HasForeignKey("NotificationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ContactLink");

                    b.Navigation("NotificationLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Notification", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Attendance", "AttendanceLink")
                        .WithMany("Notifications")
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AttendanceLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Relationship", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Parent", "ParentLink")
                        .WithMany("Relationships")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Student", "StudentLink")
                        .WithMany("Relationships")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentLink");

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Student", b =>
                {
                    b.HasOne("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Advisory", "AdvisoryLink")
                        .WithMany("Students")
                        .HasForeignKey("AdvisoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AdvisoryLink");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Advisory", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Attendance", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.ClassAdviser", b =>
                {
                    b.Navigation("Advisories");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Contact", b =>
                {
                    b.Navigation("DeliveredMsg");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Notification", b =>
                {
                    b.Navigation("DeliveredMsg");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Parent", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("SoftwareDesignQueenAnneCuriosityShopProject.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
